config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#index'
  resources :books, only: [:new, :create, :show, :index]
  namespace :librarian do
    resources :libraries do
      resources :copies
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :copies
  validates :book_id, uniqueness: true
end

app/models/copy.rb
class Copy < ApplicationRecord
 belongs_to :library
 belongs_to :book

STATUSES = ['In Library', 'On Loan', 'Other']
validates :status, presence: true, inclusion: { in: STATUSES }


end

app/models/library.rb
class Library < ApplicationRecord
  belongs_to :user
  has_many :copies
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :libraries

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || librarian_libraries_url
  end

  def render_not_found(status=:not_found)
    render plain: "#{status.to_s.titleize} :(", status: status
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.where(book_id: book_params[:book_id]).first 
    @book = Book.create!(book_params) unless @book
    redirect_to book_path(@book)
  end

  def index
    @copy = Copy.new
    @user = current_user
    @book = Book.all
  end

  def show
    @book = Book.find_by_id(params[:id])
    @user = current_user
    @copy = Copy.new
    return render_not_found if @book.blank?
  end

  private

  def book_params
    params.require(:book).permit(:isbn, :title, :book_id, :author, :subtitle, :publisher, :published_date, :description, :page_count, :cover_image_small, :cover_image_large)
  end
end

app/controllers/librarian/copies_controller.rb
class Librarian::CopiesController < ApplicationController
 before_action :authenticate_user!

def new
  @copy = Copy.new
end

def create
  @library = Library.find_by_id(params[:library_id])
  return render_not_found if @library.blank?
  @copy = @library.copies.create(copy_params)
    if @copy.valid?
      redirect_to librarian_library_path(@library)
    else
      return render_not_found(:unprocessable_entity)
    end
end

def edit
    @copy = Copy.find_by_id(params[:id])
    @library = Library.find_by_id(params[:libraryid])
    return render_not_found if @copy.blank?
    return render_not_found(:forbidden) if @copy.library.user != current_user
end

def update
    @copy = Copy.find_by_id(params[:id])
    @library = Library.find_by_id(params[:library_id])
    @book = Book.find_by_id(params[:book_id])
    return render_not_found if @copy.blank?
    return render_not_found(:forbidden) if @copy.library.user != current_user
    @copy.update_attributes(copy_params)

     if @copy.valid?
      redirect_to librarian_library_path(@copy.library)
    else
      render :edit, status: :unprocessable_entity
    end
end

def destroy
  @copy = Copy.find_by_id(params[:id])
  @library = Library.find_by_id(params[:libraryid])
  return render_not_found if @copy.blank?
  return render_not_found(:forbidden) if @copy.library.user != current_user
  @copy.destroy
  redirect_to librarian_library_path(@copy.library)
end


private

  def copy_params
    params.require(:copy).permit(:bookowner, :book_id, :status, :notes, :loanedto)
  end

end

app/controllers/librarian/libraries_controller.rb
class Librarian::LibrariesController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]


  def new
    @library = Library.new
  end

  def create
    @library = current_user.libraries.create(library_params)
    if @library.valid?
      redirect_to librarian_library_path(@library)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @library = Library.find_by_id(params[:id])
    return render_not_found if @library.blank?
    @copies = Copy.where(library_id: @library.id).order('status ASC').all
  end

  def edit
    @library = Library.find_by_id(params[:id])
    return render_not_found if @library.blank?
    return render_not_found(:forbidden) if @library.user != current_user
  end

  def update
    @library = Library.find_by_id(params[:id])
    return render_not_found if @library.blank?
    return render_not_found(:forbidden) if @library.user != current_user
    @library.update_attributes(library_params)

     if @library.valid?
      redirect_to librarian_library_path(@library)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @library = Library.find_by_id(params[:id])
    return render_not_found if @library.blank?
    return render_not_found(:forbidden) if @library.user != current_user
    @library.destroy
    redirect_to librarian_libraries_url
  end

  private

  def library_params
    params.require(:library).permit(:title, :description, :librarytype, :location)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/librarian/copies_helper.rb
module Librarian::CopiesHelper
end

app/helpers/librarian/libraries_helper.rb
module Librarian::LibrariesHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/books/index.html.erb
<div class="text-right" id="searchplace">
</div>

<h1 class="text-center DashTitle">Add A Book</h1>

<div id="content">
  <div class="text-center">
    <form id="searchbar">
      <input type="text" id="isbn" placeholder="Search">
      <button type ="submit">
        Search
      </button>
    </form>
  </div>
</div>

    <script>
      function handleResponse(response) {
        document.getElementById("searchplace").innerHTML = "<form id='searchbar'><input type='text' id='isbn' placeholder='Search'><button type ='submit'>Search</button></form>";
      for (var i = 0; i < response.items.length; i++) {
        var item = response.items[i];
        if (item.volumeInfo.subtitle === undefined) {var mySubtitle =''} else {var mySubtitle =item.volumeInfo.subtitle};
        var myBookID = String(item.id);
        var myAuthors = String(item.volumeInfo.authors);
        var myAuthors = myAuthors.replace(/,/g,', ');

        if (item.volumeInfo.imageLinks === undefined) { var bookThumb ="<tr><td rowspan='3'>Image Unavailable</td><td>"} else {

          if (item.volumeInfo.imageLinks.thumbnail === undefined) { var bookThumb = "<tr><td rowspan='3'>Image Unavailable</td><td>"} else {var bookthumb = "<tr><td rowspan='3'><img src='" + item.volumeInfo.imageLinks.thumbnail + "'></td><td>"};
        };

        document.getElementById("content").innerHTML += "<br><div class='frosted-box col-10 offset-1'><br /><div class='bookInfo'><table class='bookdisplay' cellpadding='5'><tr><td colspan='2'><h3>" + item.volumeInfo.title + "</h3></td></tr><tr><td colspan='2'>" + mySubtitle + "</td></tr>" + bookthumb + myAuthors + "</td></tr><tr><td>" + item.volumeInfo.publisher + " - " + item.volumeInfo.publishedDate +"</td></tr><tr><td rowspan='2'>" + item.volumeInfo.description + "</td></tr><tr><td valign='top'><button class='btn btn-info' onclick='submitBook(`"+myBookID+"`);' id='addbook'>Add To Library</button></td></tr></table><br /></div><br /></div>"; 
      }
    }
    </script>
   
    <script type="text/javascript">

      function sleep(milliseconds) {
        const date = Date.now();
        let currentDate = null;
        do {
          currentDate = Date.now();
        } while (currentDate - date < milliseconds);
      }

        function submitBook(bookid) {
          console.log(bookid);
        var myVolume = "https://www.googleapis.com/books/v1/volumes/" + bookid;
        var request = new XMLHttpRequest();
        request.open('GET', myVolume, true)
        request.onload = function() {
          var data = JSON.parse(this.response);
          var payload = ""
          if (request.status >= 200 && request.status < 400) {
            if (data.volumeInfo.subtitle === undefined) {var mySubtitle =''} else {var mySubtitle =data.volumeInfo.subtitle};
            var myAuthors = String(data.volumeInfo.authors);
            var myAuthors = myAuthors.replace(/,/g,', ');
            var myISBN = String(data.volumeInfo.industryIdentifiers[0].identifier)
            var payload = {
              book: {
                "title": String(data.volumeInfo.title),
                "subtitle": mySubtitle,
                "book_id": bookid,
                "isbn": myISBN,
                "author": myAuthors,
                "publisher": String(data.volumeInfo.publisher),
                "published_date": Date(data.volumeInfo.publishedDate),
                "description": String(data.volumeInfo.description),
                "page_count": Number(data.volumeInfo.pageCount),
                "cover_image_small": String(data.volumeInfo.imageLinks.thumbnail),
                "cover_image_large": String(data.volumeInfo.imageLinks.large)
              }
            };
              console.log(payload)
              $.post("/books", payload).success(function(data) {
                console.log("Successful HTTP Request");
              }).error(function(data) { 
                console.log(data)
                console.log(bookid)
              });
          } else {
            console.log('error')
          }
        };
         request.send();
      };

    </script>

    <script type="text/javascript">
      $('#searchbar').submit(function(event) {
        event.preventDefault();
        var isbn = document.getElementById('isbn').value;
        var searchTerms = isbn.replace(/ /g, "+");
        var callAPI = "https://www.googleapis.com/books/v1/volumes?q="+ searchTerms +"&callback=handleResponse";

        document.getElementById("content").innerHTML = ""

       var head= document.getElementsByTagName('head')[0];
       var script= document.createElement('script');
       script.type= 'text/javascript';
       script.src= callAPI;
       head.appendChild(script);
      });

    </script>
    <br />
  </body>

app/views/books/show.html.erb
<br />
<div class= "frosted-box col-10 offset-1  text-center">
  <br />
  <h1><%= @book.title %></h1>
  <div class="container">
    <div class="row">
      <div class="col-4">
        <% if @book.subtitle != "" %>
          <%= @book.subtitle %>
          <br /><br />
        <% end %>
        <%= @book.author %>
        <br /><br />
        <%= image_tag @book.cover_image_small, class: 'img-fluid' %>
        <br /><br />
        <%= @book.publisher %>
        <br /><br />
        Page Count: <%= @book.page_count %> &nbsp; | &nbsp; Published On: <%= @book.published_date %>
        <br /><br />
        <%= @book.description.html_safe %>
        <br /><br />
      </div>

      <div class="col-8">
        <br />
        <h3>Your Copy Information</h3>
        <br />
        <%= simple_form_for @copy, url: "#" do |f| %>
          <%= f.association :library, :collection => Library.where('user_id' => @user.id), label_method: :title, value_method: :id, include_blank: false %>
          <%= f.label :status %>
          <%= f.select :status, options_for_select(Copy::STATUSES) %>
          <br />
          <%= f.input :book_id, :as => :hidden, :input_html => { :value => @book.id } %>
          <%= f.input :bookowner, :as => :hidden, input_html: {value: @user.email}, readonly: true %>
          <br />
          <%= f.input :notes %>
          <%= f.submit "Add Copy" %>
        
        <% end %>
      </div>
    </div>
  </div>
</div>
<br />
<script>

   $('#new_copy').submit(function(event) {
    event.preventDefault();
    var data = JSON.stringify( $('#new_copy').serializeArray() );
    var data2 = JSON.parse(data)
    var copyLibrary = data2[2].value
    var copyBookowner = data2[5].value
    var copyBookID = data2[4].value
    var copyStatus = data2[3].value
    var copyNotes = data2[6].value
    console.log(copyBookID)
    var payload = {
      copy: {
        book_id: copyBookID,
        bookowner: copyBookowner,
        status: copyStatus,
        notes: copyNotes
      }
    }
    var postTo = "/librarian/libraries/" + copyLibrary + "/copies"
    console.log(postTo)
    $.post(postTo, payload).success(function(data) {
          console.log("Successful HTTP Request");
        }).error(function(data) { 
          console.log("error")
        });
  });

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Athenaeum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="mynavbar">
      <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
        <% if user_signed_in? %>
          <%= link_to 'Athenaeum', librarian_libraries_url, class: 'navbar-brand' %>
        <% else %>
          <%= link_to 'Athenaeum', root_path, class: 'navbar-brand' %>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Libraries
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item"><%= link_to 'My Libraries', librarian_libraries_url, class: "dropdown-item" %></a>
                <a class="dropdown-item"> <%= link_to 'Add a New Library', new_librarian_library_path, class: "dropdown-item" %></a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Books
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item"><%= link_to 'Add a New Book', books_url, class: "dropdown-item" %></a>
              </div>
            </li>
          </ul>
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to current_user.email, '#', class: 'nav-link' %>
              </li>
              <li class="nav-item">
                 <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>    

      <% if notice.present? %>
        <p class="alert alert-info"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>

    <!-- <div class="footer">
      <div class="container">
        <div class="foottext">
          footer info here
        </div>
      </div>
    </div> -->

  </body>
</html>

app/views/librarian/copies/edit.html.erb
<br />
<div class= "frosted-box col-10 offset-1  text-center">
  <br />
  <h1><%= @copy.book.title %></h1>
  <div class="container">
    <div class="row">
      <div class="col-4">
        <% if @copy.book.subtitle != "" %>
          <%= @copy.book.subtitle %>
          <br /><br />
        <% end %>
        <%= @copy.book.author %>
        <br /><br />
        <%= image_tag @copy.book.cover_image_small, class: 'img-fluid' %>
        <br /><br />
        <%= @copy.book.publisher %>
        <br /><br />
        Page Count: <%= @copy.book.page_count %> &nbsp; | &nbsp; Published On: <%= @copy.book.published_date %>
        <br /><br />
        <%= @copy.book.description.html_safe %>
        <br /><br />
      </div>

      <div class="col-8">
        <br />
        <h3>Edit Copy Information</h3>
        <br />
        <div>This copy belongs to:</div>
        <div>User: <%= @copy.bookowner %>. | Library: <%= @copy.library.title %></div>
        <br />
        <%= simple_form_for @copy, url: librarian_library_copy_url do |f| %>
          <%= f.label :status %>
          <%= f.select :status, options_for_select(Copy::STATUSES) %>
          <br /><br />
          <%= f.input :loanedto, label: 'Loaned to', placeholder: 'name or email' %>
          <br />
          <%= f.input :notes %>
          <%= f.submit "Save" %>
        
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/librarian/libraries/edit.html.erb
<br />
<div class="frosted-box col-10 offset-1">
  <br />
  <h1 class="sectionhead">Edit <%= @library.title %></h1>
  <%= simple_form_for @library, url: librarian_library_path(@library) do |f| %>
    <%= f.input :title, :label => "Library Name" %>
    <%= f.input :librarytype, :label => 'Type of Library' %>
    <%= f.input :description, :label => "Library Description" %>
    <%= f.input :location, :label => "Location of Library" %>
    <br />
    <%= f.submit "Edit", class: 'btn btn-primary' %>
    <br />
  <% end %>
  <br />
</div>

app/views/librarian/libraries/index.html.erb
<h1 class="text-center DashTitle">My Libraries</h1>
<% current_user.libraries.each do |library| %>
  <div class = "frosted-box col-10 offset-1">
    <br />
    <div class="row text-left editbuttons">
      <div class="library-actions float-right">
        <% if current_user && current_user == library.user %>
          <%= link_to 'Edit', edit_librarian_library_path(library) %>
          &nbsp; &nbsp;
          <%= link_to 'Delete', librarian_library_path(library), method: :delete, data: {confirm: 'Are you sure you want to delete this library?'} %>
          &nbsp; &nbsp;
          <%= link_to 'Show Library', librarian_library_path(library) %>
        <% end %>
      </div>
    </div>
    <h2 class="text-center"><%= link_to library.title, librarian_library_path(library), class: "LibraryTitle" %></h2>
    <hr class="mystyle" />
    <div class= "container">
      <div class ="row text-center">
        <div class = "col-12 LibraryDescrip">
          <%= library.description %>
        </div>
      </div>
      <br />
      <div class="row text-center rowheader">
        <div class="col-4">
          Location
        </div>
        <div class="col-4">
          Library Type
        </div>
        <div class="col-4">
          Books in <%= library.title %>
        </div>
      </div>
      <br />
      <div class="row text-center myinfo">
        <div class="col-4">
          <%= library.location %>
        </div>
        <div class="col-4">
          <%= library.librarytype %>
        </div>
        <div class="col-4">
          <%= library.copies.count %>
        </div>
      </div>
    </div>
    <br />
  </div>
  <br />
<% end %>


app/views/librarian/libraries/new.html.erb
<br />
<div class="frosted-box col-10 offset-1">
  <br />
  <h1 class="sectionhead">Add A New Library</h1>
  <%= simple_form_for @library, url: librarian_libraries_path do |f| %>
    <%= f.input :title, :label => "Library Name" %>
    <%= f.input :librarytype, :label => 'Type of Library' %>
    <%= f.input :description, :label => "Library Description" %>
    <%= f.input :location, :label => "Location of Library" %>
    <br />
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <br />
  <% end %>
  <br />
</div>

app/views/librarian/libraries/show.html.erb
<br />
<div class= "frosted-box col-10 offset-1  text-center">
  <div class="row text-left editbuttons">
    <div class="library-actions float-right">
      <% if current_user && current_user == @library.user %>
        <%= link_to 'Edit', edit_librarian_library_path(@library) %>
        &nbsp; | &nbsp;
        <%= link_to 'Delete', librarian_library_path(@library), method: :delete, data: {confirm: 'Are you sure you want to delete this library?'} %>
        &nbsp; | &nbsp;
        <%= link_to 'Add a New Book', books_url %>
      <% end %>
    </div>
  </div>
  <div class="containter-fluid">
    <div class="row">
      <div class="col-2">
        Librarian: &nbsp; 
        <br />
        <%= @library.user.email %>
      </div>
      <div class="col">
        <br />
        <h1 class= "pagehead"><%= @library.title %></h1>
        <div class= "subhead">
          <h3><%= @library.description %></h3>
        </div>
      </div>
      <div class="col-2">
        Library Type: &nbsp; 
        <br />
        <%= @library.librarytype %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm text-center">
        Library Location:&nbsp; &nbsp; <%= @library.location %>
      </div>
    </div>
  </div>
  <hr class='mystyle' data-content=" "></hr>
  <h3>In Library</h3>
  <div class="bookslist container d-flex align-content-center flex-wrap">
    <% @copies.each do |copy| %>
      <% if copy.status == 'In Library' %>
        <div class="bookdisplay2 flex-fill">
          <div class="row col-12 editbuttons justify-content-end ">
            <% if current_user && current_user == copy.library.user %>
              &nbsp; &nbsp; &nbsp;
              <%= link_to 'Edit', edit_librarian_library_copy_path(copy.library, copy) %>
              &nbsp; | &nbsp;
              <%= link_to 'Delete', librarian_library_copy_path(copy.library, copy), method: :delete, data: {confirm: 'Are you sure you want to delete this copy?'} %>
            <% end %>
          </div>
          <div class="row bookhead col-12">
            <h5><%= copy.book.title %></h5>
          </div>
          <div class="row col-12">
            <div class="col-3">
              <%= image_tag copy.book.cover_image_small, class: 'img-thumb' %>
            </div>
            <div class="col-9">
              <%= copy.book.author %>
              <br />
              Status: <%= copy.status %>
              <br />
              Collected on: <%= copy.created_at %>
              <br />
              Copy Notes
              <br />
              <%= copy.notes %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <br />
  <hr class="mystyle" />
  <h3>Out Of Library</h3>
  <div class="bookslist container d-flex align-content-center flex-wrap">
    <% @copies.each do |copy| %>
      <% if copy.status != 'In Library' %>
        <div class="bookdisplay2 flex-fill">
          <div class="row col-12 editbuttons justify-content-end ">
            <% if current_user && current_user == copy.library.user %>
              &nbsp; &nbsp; &nbsp;
              <%= link_to 'Edit', edit_librarian_library_copy_path(copy.library, copy) %>
              &nbsp; | &nbsp;
              <%= link_to 'Delete', librarian_library_copy_path(copy.library, copy), method: :delete, data: {confirm: 'Are you sure you want to delete this copy?'} %>
            <% end %>
          </div>
          <div class="row bookhead col-12">
            <h5><%= copy.book.title %></h5>
          </div>
          <div class="row col-12">
            <div class="col-3">
              <%= image_tag copy.book.cover_image_small, class: 'img-thumb' %>
            </div>
            <div class="col-9">
              <%= copy.book.author %>
              <br />
              Status: <%= copy.status %>
              <br />
              Collected on: <%= copy.created_at %>
              <br />
              Copy Notes
              <br />
              <%= copy.notes %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>

  </div>
  <br />
<br />

app/views/libraries/show.html.erb
<h1>Library page - library user</h1>

app/views/static_pages/index.html.erb

<div class="hero">
  <br />
  <div class= "frosted-box col-10 offset-1 text-center">
    <br />
    <h1 class= "pagehead">Athanaeum</h1>
    <div class= "subhead">
      <h3>Your own personal library tracker!</h3>
    </div>
    <br />
    <%= link_to 'Get Started', '#', class: 'btn btn-success' %>
    <br />
    <br />
  </div>
</div>
